name: Build ClearPix APK (Test Ads)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (repo can be empty)
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # --- NEW: Install Android NDK 27 (required by google_mobile_ads & webview packages) ---
      - name: Install Android NDK 27
        shell: bash
        run: |
          SDKBIN="${ANDROID_SDK_ROOT:-$ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager"
          echo "y" | "$SDKBIN" "ndk;27.0.12077973"
          ls -la "${ANDROID_SDK_ROOT:-$ANDROID_HOME}/ndk" || true

      - name: Create Flutter project
        run: flutter create clearpix_ai

      - name: Add AdMob plugin
        working-directory: clearpix_ai
        run: flutter pub add google_mobile_ads

      # --- NEW: Force the app to use NDK 27 ---
      - name: Force NDK version in build.gradle
        working-directory: clearpix_ai
        shell: bash
        run: |
          APP_GRADLE=android/app/build.gradle
          if grep -q 'ndkVersion' "$APP_GRADLE"; then
            sed -i 's/ndkVersion[[:space:]]*".*"/ndkVersion "27.0.12077973"/' "$APP_GRADLE"
          else
            sed -i 's/^android[[:space:]]*{$/android {\n    ndkVersion "27.0.12077973"/' "$APP_GRADLE"
          fi
          echo "Applied ndkVersion to $APP_GRADLE"
          grep -n 'ndkVersion' "$APP_GRADLE" || true

      # Replace main.dart with a TEST-ads demo that uses explicit test ad unit IDs
      - name: Write main.dart (TEST ADS)
        working-directory: clearpix_ai
        shell: bash
        run: |
          cat > lib/main.dart <<'DART'
          import 'package:flutter/material.dart';
          import 'package:google_mobile_ads/google_mobile_ads.dart';

          // Google official TEST ad unit IDs (safe for development)
          const String kBannerTestId       = 'ca-app-pub-3940256099942544/6300978111';
          const String kInterstitialTestId = 'ca-app-pub-3940256099942544/1033173712';
          const String kRewardedTestId     = 'ca-app-pub-3940256099942544/5224354917';

          Future<void> main() async {
            WidgetsFlutterBinding.ensureInitialized();
            await MobileAds.instance.initialize();
            runApp(const MyApp());
          }

          class MyApp extends StatelessWidget {
            const MyApp({super.key});
            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                debugShowCheckedModeBanner: false,
                title: 'ClearPix (Test Ads)',
                theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.indigo),
                home: const HomePage(),
              );
            }
          }

          class HomePage extends StatefulWidget {
            const HomePage({super.key});
            @override
            State<HomePage> createState() => _HomePageState();
          }

          class _HomePageState extends State<HomePage> {
            BannerAd? _banner;
            InterstitialAd? _interstitial;
            RewardedAd? _rewarded;

            @override
            void initState() {
              super.initState();
              _loadBanner();
              _preloadInterstitial();
              _preloadRewarded();
            }

            void _loadBanner() {
              final ad = BannerAd(
                size: AdSize.banner,
                adUnitId: kBannerTestId,
                request: const AdRequest(),
                listener: BannerAdListener(
                  onAdLoaded: (_) => setState(() {}),
                  onAdFailedToLoad: (ad, error) { ad.dispose(); debugPrint('Banner failed: $error'); },
                ),
              )..load();
              _banner = ad;
            }

            void _preloadInterstitial() {
              InterstitialAd.load(
                adUnitId: kInterstitialTestId,
                request: const AdRequest(),
                adLoadCallback: InterstitialAdLoadCallback(
                  onAdLoaded: (ad) => _interstitial = ad,
                  onAdFailedToLoad: (_) => _interstitial = null,
                ),
              );
            }

            void _showInterstitial() {
              final ad = _interstitial;
              if (ad == null) return;
              ad.fullScreenContentCallback = FullScreenContentCallback(
                onAdDismissedFullScreenContent: (ad) { ad.dispose(); _preloadInterstitial(); },
                onAdFailedToShowFullScreenContent: (ad, e) { ad.dispose(); _preloadInterstitial(); },
              );
              ad.show();
              _interstitial = null;
            }

            void _preloadRewarded() {
              RewardedAd.load(
                adUnitId: kRewardedTestId,
                request: const AdRequest(),
                rewardedAdLoadCallback: RewardedAdLoadCallback(
                  onAdLoaded: (ad) => _rewarded = ad,
                  onAdFailedToLoad: (_) => _rewarded = null,
                ),
              );
            }

            Future<void> _showRewarded() async {
              final ad = _rewarded;
              if (ad == null) { _preloadRewarded(); return; }
              ad.fullScreenContentCallback = FullScreenContentCallback(
                onAdDismissedFullScreenContent: (ad) { ad.dispose(); _preloadRewarded(); },
                onAdFailedToShowFullScreenContent: (ad, e) { ad.dispose(); _preloadRewarded(); },
              );
              await ad.show(onUserEarnedReward: (_, __) {});
              _rewarded = null;
            }

            @override
            void dispose() {
              _banner?.dispose();
              _interstitial?.dispose();
              _rewarded?.dispose();
              super.dispose();
            }

            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(title: const Text('ClearPix (Test Ads)')),
                body: Column(
                  children: [
                    const Expanded(
                      child: Center(
                        child: Text(
                          'Demo app using Google TEST ads.\nReplace IDs with your real ones only for release.',
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                    if (_banner != null)
                      SizedBox(
                        width: _banner!.size.width.toDouble(),
                        height: _banner!.size.height.toDouble(),
                        child: AdWidget(ad: _banner!),
                      ),
                  ],
                ),
                floatingActionButton: Wrap(
                  spacing: 12,
                  children: [
                    FloatingActionButton.extended(
                      onPressed: _showInterstitial,
                      icon: const Icon(Icons.play_circle),
                      label: const Text('Interstitial'),
                    ),
                    FloatingActionButton.extended(
                      onPressed: _showRewarded,
                      icon: const Icon(Icons.card_giftcard),
                      label: const Text('Rewarded'),
                    ),
                  ],
                ),
              );
            }
          }
          DART

      - name: Patch AndroidManifest (TEST App ID + Internet)
        working-directory: clearpix_ai
        shell: bash
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          # INTERNET permission
          if ! grep -q 'android.permission.INTERNET' "$MANIFEST"; then
            sed -i 's|<manifest|<manifest>\n    <uses-permission android:name="android.permission.INTERNET" />|' "$MANIFEST"
          fi
          # Google TEST app ID meta-data
          if ! grep -q 'com.google.android.gms.ads.APPLICATION_ID' "$MANIFEST"; then
            sed -i 's|<application|<application>\n        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713" />|' "$MANIFEST"
          fi

      - name: flutter pub get
        working-directory: clearpix_ai
        run: flutter pub get

      - name: Build release APK
        working-directory: clearpix_ai
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clearpix-test-apk
          path: clearpix_ai/build/app/outputs/flutter-apk/app-release.apk
